# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a24c7eca3f09a0b83bc09f43359b81dd82a3b79bde1a06d81f58c1f6c707bee7d4586d59a08060f107d283e9e50646549ebec973edc88a1d75b71782ecbf517

test:
  secret_key_base: 97caecc93bf1486cdd2145e81df969e1d298681fc52ce5e2d096e109505940684283dd62c928a49ec1b48af970aaa12e3fd7eaf865332682dc529913331cec38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
